dataStreamer.writeNumber(1 / 5);
dataStreamer.writeLine("");
dataStreamer.writeNumber(20 / 3);
dataStreamer.writeLine("");
dataStreamer.writeNumber(400 / 35);
dataStreamer.writeLine("");
dataStreamer.writeNumber(1000 / 2);
dataStreamer.writeLine("");
dataStreamer.writeNumber(1002);
dataStreamer.writeLine("");
dataStreamer.writeNumber(10000002 / 458);
dataStreamer.writeLine("");
dataStreamer.writeNumber(0);
dataStreamer.writeLine("");
dataStreamer.writeNumber(-1);
dataStreamer.writeLine("");
dataStreamer.writeNumber(-1000 / 3);
dataStreamer.writeNumbers([5, 2 / 5, 44 / 444, 5 / 5]);